### ISSUE TITLE
Clear report body fields based on `phase` and report destination

### ISSUE THREAD

**Issue by chlily1** [w3c/network-error-logging#105]
NEL reports include information about the request that doesn't seem necessary for troubleshooting certain types of errors.

Some of these fields are cleared when non-DNS-phase reports are "downgraded", but such downgrading is not applied to all DNS and connection phase errors.

For troubleshooting DNS phase errors, only the hostname (not the full URL) is relevant, i.e., the path and query can be omitted. The `server_ip`, `response_headers`, and `status_code` won't be available, but the `referrer`, `protocol`, `method`, and `request_headers` are included in the report despite not being relevant to DNS resolution or available to DNS servers.

For troubleshooting connection phase errors, the full URL is also not necessary, nor are the `request_headers` and `method`.

To protect privacy, should these fields be cleared depending on the error phase? Or perhaps, to prevent unnecessary leakage of information across origins, should they be cleared only if the collecting Reporting endpoint does not share an origin with the NEL policy?

Would the following be reasonable to protect privacy while still retaining the utility of NEL?:

- For DNS phase reports, only `sampling_fraction`, `elapsed_time`, `phase`, and `type` are included in report bodies, and the URL is truncated to the origin only.
- For connection phase reports, only `server_ip`, `protocol`, `sampling_fraction`, `elapsed_time`, `phase`, and `type` are included in report bodies, and the URL is truncated to the origin only.
- For other phases (i.e. application phase), all report body fields and the full URL are included in reports to the same origin, but only the origin portion of the URL, `sampling_fraction`, `elapsed_time`, `phase`, and `type` are included in reports to a different origin.

**Comment by chlily1** [comment]
Correction: `server_ip` might be non-empty for a DNS phase report if it is a downgraded `dns.address_changed` report, in which case it should be included in the report.

**Comment by aaronpeters** [comment]
> To protect privacy, should these fields be cleared depending on the error phase?

+1 for this. Useless data is ... useless.

> Or perhaps, to prevent unnecessary leakage of information across origins, should they be cleared only if the collecting Reporting endpoint does not share an origin with the NEL policy?

I predict many origins will use a third party service for collecting NEL reports, just like many origins do this to collect RUM performance data today.
If the origin trusts a third party to be the Reporting endpoint, that is their choice and it should not result in loss of data and insights.

E.g. for application phase reports, reducing the URL to only the origin portion of the URL (`https://www.nike.com/shoes/men/sale` becomes `https://www.nike.com`) would basically render a third party service useless as a Reporting endpoint.
As a DevOps engineer at Nike, I want to know which URLs returned 400 errors, not just which origins.

**Comment by clelland** [comment]
Discussed at TPAC - It sounds like everyone is in favor of removing the non-essential information from DNS and Connection phase reports, but that we should really keep the ability to have the URL in application phase reports, regardless of endpoint. 

I think that #151, however, can be used to reduce the URL exposure if site owners want to do that.

**Comment by martinthomson** [comment]
The sense of the room at TPAC was that this was a good idea, though we did not get into the details of which fields could be redacted (that said, cookies #112, #111 were definitely considered worth dropping).

I would be supportive of having some text about giving browsers the option to perform additional redaction of fields if they are concerned about leaking sensitive information.

**Comment by martinthomson** [comment]
Additional reasons to exclude `server_ip`, beyond those already mentioned (i.e., for application phase), might be:

* When a proxy is in use (here, the IP might not be known)
* When the server is authenticated using a certificate that chains to a trust anchor that is not in the usual trust store (i.e., the connection has been intercepted by an intermediary that has been authorized via the insertion of a trust anchor in the client)

These are also two cases where knowing that this has happened might be very good information for diagnosing problems.  After all, these systems are very often the cause of problems.  While it might be worthwhile to build new attributes to signal that these systems are in use, we should not be leaking details of their configuration.

**Comment by clelland** [comment]
> * When a proxy is in use (here, the IP might not be known)

What sort of proxy do you mean here, @martinthomson? I agree that if the user agent is configured to use a proxy server, we definitely shouldn't be reporting its IP address, and should probably remove `server_ip` from those reports. If the architecture of the web site uses a transparent proxy / load balancer / etc, then I think we can still report the public IP address of the site.

**Comment by martinthomson** [comment]
A forward proxy.  Transparent proxies are a terrible idea, but we won't see them if they choose to try to insert themselves.  Gateways and load balancers are the server and those are totally fine here.

**Comment by clelland** [comment]
Just realized that I've been using the phrase "transparent proxy" to mean "reverse proxy" recently. Agreed that a transparent proxy is not observable from the browser, and we can't do anything in that case.

I'll add some text (also to close #121) to cover that, and say that we should exclude `server_ip` if the browser has been configured to use a proxy server rather than connecting directly to the origin.
