### ISSUE TITLE
NEL cache should be partitioned

### ISSUE THREAD

**Issue by yoavweiss** [w3c/network-error-logging#138]
#136 and the [related paper](https://arxiv.org/pdf/2305.05343.pdf) point out an issue with the fact that the NEL cache is not partitioned. While in [practice](https://groups.google.com/a/chromium.org/g/blink-dev/c/Oj9cS6p40Ws?pli=1) it is partitioned in Chromium, we should fix the spec to reflect that.

**Comment by clelland** [comment]
@jyasskin suggested that we can use the [storage key](https://storage.spec.whatwg.org/#storage-key) concept from https://github.com/whatwg/storage as a partition key in this spec.

I think we'd need a note that implementers can use stronger keys, but that should set a minimum bar. And then if Storage adopts double- or triple-keying, NEL should get that for free at that point.

**Comment by annevk** [comment]
Shouldn't it use the network partition key?

**Comment by clelland** [comment]
Is that concept defined in a spec? I can imagine that it would be a better fit, but I'm not certain

**Comment by annevk** [comment]
Yes, in Fetch.
