### ISSUE TITLE
Report-To: {"endpoints":{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=ETcZDK308tPXIcI8k4EK6CpOy6EZbQAti1VMop765bZHMTlFClnF6qT8OBb93AeAVO9pgxakliCDtYfKJbrcJGc4lQ3ZoUCz4RORxa%2FEgAZHPmqmdWdJTJf5oyACWHo5WQ%3D%3D"},"group":"cf-nel","max_age":604800}

### ISSUE THREAD

**Issue by rkabiri1988** [w3c/network-error-logging#142]
Report-To: {"endpoints":{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=ETcZDK308tPXIcI8k4EK6CpOy6EZbQAti1VMop765bZHMTlFClnF6qT8OBb93AeAVO9pgxakliCDtYfKJbrcJGc4lQ3ZoUCz4RORxa%2FEgAZHPmqmdWdJTJf5oyACWHo5WQ%3D%3D"},"group":"cf-nel","max_age":604800}

**Comment by clelland** [comment]
Closing, as this does not appear to be an actual statement of an issue. Please re-open if you can clarify that at all.
