### ISSUE TITLE
Auto-publishing to /TR/ is failing

### ISSUE THREAD

**Issue by clelland** [w3c/network-error-logging#161]
It looks like the published version of NEL at [https://www.w3.org/TR/network-error-logging/](https://www.w3.org/TR/network-error-logging/) is ~5 years out of date. We should be auto-publishing, but I think that the deploy step is failing somewhere.

@caribouW3, can you take a look and see what we're doing wrong here?

**Comment by caribouW3** [comment]
Fixed!

**Comment by clelland** [comment]
Thanks!
