### ISSUE TITLE
secure transport errors or warnings

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/network-error-logging#35]
The spec says... 

> If the policy is delivered over a secure transport with no underlying secure transport errors or warnings

This will probably differ amongst browsers (specially in the warning part). I'm not sure how enforceable this is as a MUST requirement.

**Comment by igrigorik** [comment]
I think that's OK though. One UA might be more strict than another in how it enforces its security rules, and we can't define or anticipate these rules in the spec. I think the intent is clear and we leave this up to the UA to interpret.

**Comment by igrigorik** [comment]
Closing, feel free to reopen if you think this requires more work.
