### ISSUE TITLE
Mixed content 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/network-error-logging#36]
Spec says: 

> The application does not need to be HTTPS-only to take advantage of NEL...

Sorry, I always get confused about this ... but won't fetching the pixel get blocked by MIX? I can't remember if it's possible to go from HTTP to HTTPS and if that is ok. If it's ok, just ignore this :)

**Comment by igrigorik** [comment]
That note is talking about registration: the registration MUST happen over HTTPS, but the application does not need to be HTTPS-only to register, it can simply fetch an "HTTPS pixel" from an `http://`origin. Fetching HTTPS from HTTP page is fine.. in fact, it's encouraged.
