### ISSUE TITLE
directive names not in ABNF?

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/network-error-logging#37]
The spec says: 

> This specification defines three NEL directives: <a>report-uri</a>, <a>max-age</a>, and <a>includeSubDomains</a>. 

I would have expected the directive names to be in the ABNF? I think it would be helpful if they were and were part of the ABNF definition.

**Comment by igrigorik** [comment]
They are defined in their respective sections, I think we're ok? Feel free to reopen.
