### ISSUE TITLE
Processing directive fields 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/network-error-logging#38]
Spec says 
> The overall requirements for directives are: ... 

This sounds like a directive field processor... and in fact, it has processing rules like "All directives MUST appear only once in an NEL header field" etc.

I haven't finished reading the spec yet, but if there is a processor defined later, then this is redundant (or could be non-normative). If there is no processor, then you should consider defining one.

**Comment by igrigorik** [comment]
Hmm, this ("directive") is just standard HTTP language, and since we're talking about a response header field, I don't think we need to define anything on our own here. Closing, but feel free to reopen.
