### ISSUE TITLE
repeated secure transport requirement 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/network-error-logging#39]
The spec says: 

> Each `<a title="report-uri">`report URL`</a>` in the provided `<a>`set of report URLs`</a>` MUST use a secure transport to receive the NEL reports. If any of the provided `<a title="report-uri">`report URL's`</a>` does not use a secure transport, the user agent MUST ignore the provided policy. The process of sending network error reports to the specified URL's in this directive's value is defined in this documents `<a href="#reporting"></a>` section

I'm pretty sure you said this before, also as a requirement (hence this is a duplicate). Maybe make the first one non-normative?

**Comment by igrigorik** [comment]
There are different requirements here: earlier declaration requires that registration happens over a secure transport; here we're indicating that the specified report URL must also use a secure transport to receive the reports.
