### ISSUE TITLE
Clarify report delivery to be restricted to https scheme

### ISSUE THREAD

**Issue by igrigorik** [w3c/network-error-logging#46]
_(Feedback from @mcmanus)_

> the text describes a secure transport as e.g. TLS, but I think you mean the transaction is carried with an https scheme. (e.g. would a http:// transaction carried out of the UA to a https proxy qualify? nope.)

**Comment by yoavweiss** [comment]
Maybe we should define it to so that it'd be restricted to secure origins/contexts? I'm not sure what's the ideal definition to hook up to, but it'd be great if we could define it so it'd work for localhost (and can be tested without extra cert hassle).

/cc @mikewest

**Comment by mikewest** [comment]
You're looking for "privileged context", as in https://w3c.github.io/webappsec/specs/powerfulfeatures/#new.

**Comment by igrigorik** [comment]
@yoavweiss @mikewest thanks guys, updated. PTAL @ 978260c. 

Note that there are a few other mentions of "secure transport" in the spec, but those will be resolved as part of #42.
