### ISSUE TITLE
DNS errors?

### ISSUE THREAD

**Issue by annevk** [w3c/network-error-logging#48]
Wouldn't this allow even more reliable mapping of a network behind a firewall?

**Comment by igrigorik** [comment]
As a practical means, not sure.. let's try to work through it. Do you have any particular examples in mind for how you'd (ab)use NEL to do this?

/cc @sleevi @mikewest

**Comment by dcreager** [comment]
I think this was covered in detail in #74, which was resolved by #83.  Closing this; please reopen or file a new issue if there are additional examples that we didn't cover.
