### ISSUE TITLE
Header syntax

### ISSUE THREAD

**Issue by mnot** [w3c/network-error-logging#52]
Must as with server-timing, NEL is NOT defined as a comma-delimited field. If we want multiple instances of the header to be combined, e.g.,

    NEL: report-URI="/"
    NEL: max-age=3600

then it needs to be comma-delimited. Otherwise, if we really want to use semicolons, we'll need to define error handling for multiple fields.

Also, it would be good to strongly caution people to quote report-uri when producing the header, so that there aren't issues with delimiters in URIs.

Do we really want the registry of directives to be under IETF Review rules? That seems odd, considering the W3C is producing this spec; also, the IETF may not want to...

See also:
  http://httpwg.github.io/specs/rfc7231.html#considerations.for.new.header.fields

**Comment by igrigorik** [comment]
I think we want to restrict it to a single header field:

* a valid NEL header field must contain all of the directives
* if multiple NEL header fields are present, UA should process first valid NEL field and ignore the rest
* stick with semicolons to be consistent with CSP.. What do you have in mind for error handling here?

**Comment by igrigorik** [comment]
@mnot please take a look at #53. Warmer? :)

**Comment by mnot** [comment]
Left one note on the changeset, but looks more reasonable. A caution to quote report-url would still be good.
