### ISSUE TITLE
Specify a maximum 'max-age'

### ISSUE THREAD

**Issue by sleevi** [w3c/network-error-logging#65]
https://wicg.github.io/network-error-logging/#the-max-age-field describes the syntactical format of the max-age, but doesn't describe whether or not any additional limits should be imposed on this field - for example, nothing greater than 30 days.

It seems that there are both privacy and security implications related to this field.

**Comment by dcreager** [comment]
We've resolved the security and privacy implications of this field (to prevent things like DNS rebinding) in #74 and #83.  Other specs that have a `max-age` field don't have explicit maximums (HSTS, CORS), so I think we should mimic that.
