### ISSUE TITLE
Clarify when reports are sent

### ISSUE THREAD

**Issue by sleevi** [w3c/network-error-logging#66]
https://wicg.github.io/network-error-logging/#reporting specifies when reports are sent; unfortunately, it's lacking specificity to allow for interoperable implementations.

Given a definition of `A network error is any condition where a connection or a protocol error is encountered by the user agent`, an example scenario that is unclear is when a client is performing a [Happy Eyeballs](https://en.wikipedia.org/wiki/Happy_Eyeballs) fallback, should the failure of the second connection result in a report?

Defining 'network error' in terms of the [Fetch Standard](https://fetch.spec.whatwg.org/) state machine may provide more interoperability.

**Comment by dcreager** [comment]
I think the new language from #74 and #83 clarifies this.  We can re-open if we need even more detail.
