### ISSUE TITLE
Move sampling rate into Reporting?

### ISSUE THREAD

**Issue by dcreager** [w3c/network-error-logging#71]
On the WebPerf WG call last week someone asked whether it would make sense to move the sampling rate logic from the NEL spec into the Reporting spec, so that it would be more easily reusable across other specs.  (This was brought up earlier on the Reporting side in [reporting#45](/WICG/reporting/issues/45).)

The only wrinkle here is that NEL currently lets you set different sampling rates for successes and failures.  If we move sampling rates into Reporting, we would need to either (a) make Reporting somehow allow multiple sampling rates per endpoint group (yuck), or (b) update NEL to let you choose different endpoint groups for successes and failures.

**Comment by dcreager** [comment]
Per wicg/reporting#45, we're leaving sampling rates in the dependent specs for now, and not moving anything into Reporting until we have >1 concrete examples to design from.

**Comment by clelland** [comment]
Closing this now, as #124 and #133 are also both pulling in a separate direction, with configurable sampling rates based on different NEL error properties.
