### ISSUE TITLE
Network Error Report body fields discrepancy

### ISSUE THREAD

**Issue by JohnRiv** [w3c/network-error-logging#78]
In [3.1 Network error reports](http://wicg.github.io/network-error-logging/#network-error-reports), it says the following fields should be included in the network error report's body:

- [x] uri
- [x] referrer
- [ ] sampling_fraction
- [x] server_ip
- [x] protocol
- [x] status_code
- [x] elapsed_time
- [x] type

However, the 2 examples in [3.6.2 Sample Network Error Reports](http://wicg.github.io/network-error-logging/#sample-network-error-reports) use these fields:

- [x] uri
- [x] referrer
- [x] server_ip
- [x] protocol
- [x] status_code
- [x] elapsed_time
- [ ] age
- [x] type

As you can see, **3.1** includes `sampling_fraction` and no `age`, while **3.6.2** includes `age` and no `sampling_fraction`.

`age` appears to be covered by the [Reporting API](https://wicg.github.io/reporting/#try-delivery), so I assume the examples just need to be updated to not include `age` and instead include a `sampling-rate`.

**Comment by dcreager** [comment]
Yes you're right!  I need to update the examples, thanks for catching this.

**Comment by dcreager** [comment]
Updated in #81; should be live on the spec page once that PR gets merged.

**Comment by JohnRiv** [comment]
Thanks Doug!
