### ISSUE TITLE
Should reports have 'phase' property?

### ISSUE THREAD

**Issue by ScottHelme** [w3c/network-error-logging#94]
The spec defines that the report body should have a 'phase' property that should be set to 'dns', 'connection' or 'application': https://www.w3.org/TR/network-error-logging/#generate-a-network-error-report

None of the example reports in the spec contain this property. Should the property be present on example reports or should the 'phase' property be removed from the report body?

**Comment by dcreager** [comment]
Ah, good catch!  The sample reports should have a `phase`.  Thanks for catching this, I'll whip up a patch real quick!

**Comment by ScottHelme** [comment]
Any news on when this change will be reflected in the spec?

**Comment by dcreager** [comment]
I think I updated the examples in the spec in #95, are you still seeing them missing?  Which URL are you using for the spec?  (Latest draft should be [here](https://w3c.github.io/network-error-logging/).)

**Comment by ScottHelme** [comment]
Oops wrong link :) 

https://www.w3.org/TR/network-error-logging-1/
